# Assignment 12

# Text Mining:- Elon Musk

In [1]:
from matplotlib.pyplot import imread
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import string
import spacy
%matplotlib inline

In [2]:
elon = pd.read_csv(r'C:\Users\Suraj\Desktop\Data Science\Assignment 12 Text Mining\Elon_musk.csv', encoding='unicode_escape')
elon

Unnamed: 0                                               Text
0              1                             @kunalb11 I’m an alien
1              2  @ID_AA_Carmack Ray tracing on Cyberpunk with H...
2              3                @joerogan @Spotify Great interview!
3              4                    @gtera27 Doge is underestimated
4              5  @teslacn Congratulations Tesla China for amazi...
...          ...                                                ...
1994        1995  @flcnhvy True, it sounds so surreal, but the n...
1995        1996  @PPathole Make sure to read ur terms &amp; con...
1996        1997                @TeslaGong @PPathole Samwise Gamgee
1997        1998  @PPathole Altho Dumb and Dumber is <U+0001F525...
1998        1999                          Progress update August 28

[1999 rows x 2 columns]

In [3]:
 x = elon['Text']

In [4]:
elon = [x.strip() for x in x]
elon = [x for x in elon if x]

In [5]:
text = ' '.join(elon)
len(text)

158702

In [6]:
no_punc_text = text.translate(str.maketrans(' ', ' ', string.punctuation))

In [7]:
from nltk.tokenize import word_tokenize

In [8]:
text_tokens = word_tokenize(no_punc_text)
print(text_tokens)
len(text_tokens)

['kunalb11', 'I\x92m', 'an', 'alien', 'IDAACarmack', 'Ray', 'tracing', 'on', 'Cyberpunk', 'with', 'HDR', 'is', 'nextlevel', 'Have', 'you', 'tried', 'it', 'joerogan', 'Spotify', 'Great', 'interview', 'gtera27', 'Doge', 'is', 'underestimated', 'teslacn', 'Congratulations', 'Tesla', 'China', 'for', 'amazing', 'execution', 'last', 'year', 'Now', 'on', 'to', 'the', 'next', 'for', 'even', 'more', 'Happy', 'New', 'Year', 'of', 'the', 'Ox', 'httpstco9WFKMYu2oj', 'Frodo', 'was', 'the', 'underdoge', 'All', 'thought', 'he', 'would', 'fail', 'Himself', 'most', 'of', 'all', 'httpstcozGxJFDzzrM', 'OwenSparks', 'flcnhvy', 'anonyx10', 'Haha', 'thanks', 'flcnhvy', 'anonyx10', 'Indeed', 'Tweets', 'definitely', 'do', 'not', 'represent', 'realworld', 'time', 'allocation', 'The', 'most', 'entertaining', 'outcome', 'is', 'the', 'most', 'likely', 'GiveDirectly', 'Just', 'sent', 'some', 'Just', 'agree', 'to', 'do', 'Clubhouse', 'with', 'kanyewest', 'httpstco3rWE9uHSTS', 'geoffkeighley', 'UnrealEngine', 'It\x9

21078

In [9]:
with open(r"C:\Users\Suraj\Desktop\Data Science\Assignment 12 Text Mining\stop.txt") as f:
    stop_words = f.read()

In [10]:
no_stop_tokens = [word for word in text_tokens if not word in stop_words]
print(no_stop_tokens)

['kunalb11', 'I\x92m', 'alien', 'IDAACarmack', 'Ray', 'tracing', 'Cyberpunk', 'HDR', 'nextlevel', 'Have', 'joerogan', 'Spotify', 'Great', 'interview', 'gtera27', 'Doge', 'underestimated', 'teslacn', 'Congratulations', 'Tesla', 'China', 'amazing', 'execution', 'year', 'Now', 'Happy', 'New', 'Year', 'Ox', 'httpstco9WFKMYu2oj', 'Frodo', 'underdoge', 'All', 'thought', 'fail', 'Himself', 'httpstcozGxJFDzzrM', 'OwenSparks', 'flcnhvy', 'anonyx10', 'Haha', 'flcnhvy', 'anonyx10', 'Indeed', 'Tweets', 'represent', 'realworld', 'allocation', 'The', 'entertaining', 'outcome', 'GiveDirectly', 'Just', 'Just', 'agree', 'Clubhouse', 'kanyewest', 'httpstco3rWE9uHSTS', 'geoffkeighley', 'UnrealEngine', 'It\x92s', 'Bought', 'Dogecoin', 'lil', 'X', 'toddler', 'hodler', 'JoshManMode', 'He', 'issues', 'sentencing', 'bit', 'high', 'freewalletorg', 'Thanks', 'fixing', 'freewalletorg', 'Please', 'unlock', 'account', 'AstroJordy', 'U0001F923U0001F923', 'This', 'true', 'power', 'haha', 'httpstcoFc9uhQSd7O', 'freew

In [11]:
lower_words = [x.lower() for x in no_stop_tokens]

In [12]:
from nltk.stem import PorterStemmer

In [13]:
ps = PorterStemmer()
stemmed_tokens = [ps.stem(word) for word in lower_words]

In [14]:
nlp = spacy.load('en_core_web_sm')

In [15]:
doc = nlp(' '.join(lower_words))

In [16]:
lemmas = [token.lemma_ for token in doc]
print(lemmas)

['kunalb11', 'i\x92m', 'alien', 'idaacarmack', 'ray', 'tracing', 'cyberpunk', 'hdr', 'nextlevel', 'have', 'joerogan', 'spotify', 'great', 'interview', 'gtera27', 'doge', 'underestimate', 'teslacn', 'congratulation', 'tesla', 'china', 'amazing', 'execution', 'year', 'now', 'happy', 'new', 'year', 'ox', 'httpstco9wfkmyu2oj', 'frodo', 'underdoge', 'all', 'think', 'fail', 'himself', 'httpstcozgxjfdzzrm', 'owenspark', 'flcnhvy', 'anonyx10', 'haha', 'flcnhvy', 'anonyx10', 'indeed', 'tweet', 'represent', 'realworld', 'allocation', 'the', 'entertaining', 'outcome', 'givedirectly', 'just', 'just', 'agree', 'clubhouse', 'kanyew', 'httpstco3rwe9uhst', 'geoffkeighley', 'unrealengine', 'it\x92s', 'buy', 'dogecoin', 'lil', 'x', 'toddler', 'hodler', 'joshmanmode', 'he', 'issue', 'sentence', 'bit', 'high', 'freewalletorg', 'thank', 'fix', 'freewalletorg', 'please', 'unlock', 'account', 'astrojordy', 'u0001f923u0001f923', 'this', 'true', 'power', 'haha', 'httpstcofc9uhqsd7o', 'freewalletorg', 'any', 'c

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
cv = CountVectorizer()
X = cv.fit_transform(lemmas)
sum_words = X.sum(axis = 0)
words_freq = ([word, sum_words[0, idx]] for word, idx in cv.vocabulary_)

In [19]:
print(cv.get_feature_names())

['005', '10', '100', '1000', '10000', '107', '10x', '11', '112', '11thhour', '12', '122', '13', '130pm', '13arm13arm', '13ericralph31', '14', '140pm', '149watt', '14yearold', '15', '150', '155', '16', '162', '17', '18', '1880', '1b', '1matthewgarcia', '1st', '1stprinciples4l', '20', '200', '2007', '2008', '2009', '2012', '2017', '2020', '2021', '2024', '2026', '2030', '20k', '210', '218', '21st', '22', '225', '23', '230', '24', '240am', '247teslanews', '25', '250', '250kw', '25d', '25gunsteslacom', '25k', '25th', '28', '28delayslater', '28th', '29', '2k', '2nd', '2v', '30', '300', '301', '304', '304l', '31', '33', '330', '360', '37', '3800', '394', '39a', '3d', '3rd', '40', '400', '42', '420', '4227', '430', '43rd', '445pm', '448', '4530000', '45thspacewing', '4680', '479000', '48', '4d', '4th', '4thfromourstar', '50', '50000', '50k', '60', '60000', '65', '69420', '6f', '6k', '727', '727pm', '74', '78', '7th', '90', '9007', '91demigod', '922', '948', '95', '99', '9inety6prince', 'aber'

In [20]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
X2 = vectorizer2.fit_transform(lemmas)

In [22]:
print(vectorizer2.get_feature_names())

['do and', 'there ll', 'they re', 'today within', 'we ll', 'we re', 'we ve', 'would ve', 'you ll', 'you re', 'you ve']


In [23]:
print(X2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [24]:
afinn = pd.read_csv(r"C:\Users\Suraj\Desktop\Data Science\Assignment 12 Text Mining\Afinn.csv", encoding='unicode_escape')

In [25]:
afinn.shape

(2477, 2)

In [26]:
from itertools import islice

In [27]:
def take(n, iterable):
    return list(islice(iterable, n))

In [28]:
affinity_scores = afinn.set_index('word')['value'].to_dict()
take(20, affinity_scores.items())

[('abandon', -2),
 ('abandoned', -2),
 ('abandons', -2),
 ('abducted', -2),
 ('abduction', -2),
 ('abductions', -2),
 ('abhor', -3),
 ('abhorred', -3),
 ('abhorrent', -3),
 ('abhors', -3),
 ('abilities', 2),
 ('ability', 2),
 ('aboard', 1),
 ('absentee', -1),
 ('absentees', -1),
 ('absolve', 2),
 ('absolved', 2),
 ('absolves', 2),
 ('absolving', 2),
 ('absorbed', 1)]

In [29]:
from nltk import tokenize
sentences = tokenize.sent_tokenize(" ".join(elon))

In [30]:
sent_df = pd.DataFrame(sentences, columns=['sentences'])

In [31]:
nlp = spacy.load('en_core_web_sm')

In [32]:
sentiment_lexicon = affinity_scores
def calculate_sentiment(text: str=None) -> float:
    sent_score = 0
    if text:
        sentence = nlp(text)
        for word in sentence:
            sent_score += sentiment_lexicon.get(word.lemma_, 0)
    return sent_score

In [33]:
calculate_sentiment(text = 'very sad')

-2

In [34]:
sent_df['sentiment_value'] = sent_df['sentences'].apply(calculate_sentiment)
sent_df['sentiment_value']

0      0
1      0
2      3
3      3
4      0
      ..
919    0
920   -4
921    0
922   -2
923    0
Name: sentiment_value, Length: 924, dtype: int64

In [35]:
sent_df['word_count'] = sent_df['sentences'].str.split().apply(len)
sent_df['word_count'] 

0      13
1       4
2       4
3      13
4       8
       ..
919    11
920    31
921     3
922    47
923    15
Name: word_count, Length: 924, dtype: int64

In [36]:
sent_df['word_count'].head(10)

0     13
1      4
2      4
3     13
4      8
5      6
6     14
7     10
8      8
9    109
Name: word_count, dtype: int64

In [37]:
sent_df.sort_values(by = 'sentiment_value').tail(10)

sentences  sentiment_value  \
183  There’s some great AI out ther
 https://t.co/v...               10   
224  @PPathole @karpathy For a second there, I thou...               11   
817  Might be able to
 https://t.co/FB7e5nOq2E @Pri...               11   
184  Also, w
 https://t.co/IYdKttVsqk @cleantechnic...               12   
645  It’s
 https://t.co/IxhyT6NuiC @Teslarati Tesla...               13   
81   @teslaownersSV This is a good one @MrBeastYT I...               13   
585  The “open” areas
 https://t.co/rabjKrtQlw @Sav...               14   
719  We just haven’t observed the
 https://t.co/mez...               15   
36   @ajtourville @Erdayastronaut @SpaceX Yes, but ...               15   
105  @Erdayastronaut @SpaceX Was also thinking that...               16   

     word_count  
183          48  
224          69  
817          72  
184          98  
645          65  
81           38  
585         138  
719          72  
36          231  
105          94

In [38]:
sent_df['sentiment_value'].describe()

count    924.000000
mean       1.352814
std        2.671421
min       -8.000000
25%        0.000000
50%        0.000000
75%        3.000000
max       16.000000
Name: sentiment_value, dtype: float64

In [39]:
sent_df[sent_df['sentiment_value']<=0]

sentences  sentiment_value  \
0    @kunalb11 I’m an alien @ID_AA_Carmack Ray trac...                0   
1                                   Have you tried it?                0   
4                   Now on to the next for even more!!                0   
6    https://t.co/9WFKMYu2oj Frodo was the underdog...               -2   
8    Tweets definitely do not represent real-world ...                0   
..                                                 ...              ...   
919  @kenyanwalstreet Not actually a payout, just a...                0   
920  It may never pay out, as the stock can’t b
 ht...               -4   
921                                    Details Aug 28.                0   
922  AI symbiosis while u wait @vistacruiser7 @flcn...               -2   
923  @TeslaGong @PPathole Samwise Gamgee @PPathole ...                0   

     word_count  
0            13  
1             4  
4             8  
6            14  
8             8  
..          ...  
919          11  
920          31  
921           3  
922          47  
923          15  

[496 rows x 3 columns]

In [40]:
sent_df[sent_df['sentiment_value']>=0]

sentences  sentiment_value  \
0    @kunalb11 I’m an alien @ID_AA_Carmack Ray trac...                0   
1                                   Have you tried it?                0   
2                  @joerogan @Spotify Great interview!                3   
3    @gtera27 Doge is underestimated @teslacn Congr...                3   
4                   Now on to the next for even more!!                0   
..                                                 ...              ...   
917               This is both great &amp; terrifying.                3   
918  Everything we’ve ever sensed or thought has be...                2   
919  @kenyanwalstreet Not actually a payout, just a...                0   
921                                    Details Aug 28.                0   
923  @TeslaGong @PPathole Samwise Gamgee @PPathole ...                0   

     word_count  
0            13  
1             4  
2             4  
3            13  
4             8  
..          ...  
917           6  
918          17  
919          11  
921           3  
923          15  

[814 rows x 3 columns]